name: Routes Coverage

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  gh-actions:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - 4.12.x

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          dune-cache: true
          opam-depext-flags: --with-test

      - name: Install bisect_ppx
        run: opam depext bisect_ppx --install

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Run tests
        run: |
          sed -i 's/library/library (preprocess (pps bisect_ppx))/g' src/dune
          opam exec -- dune runtest
          opam exec -- bisect-ppx-report send-to Coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ github.token }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
